variables:
  # doesn't seem to be any way to define this via env var
  - &secctx-backend-options
    kubernetes:
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

when:
  - event: push
    branch: main
  - event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
    backend_options: *secctx-backend-options

steps:
  - name: format & cache
    image: nixos/nix
    environment:
      ATTIC_TOKEN:
        from_secret: ATTIC_TOKEN
    commands:
      # use only attic cache, enable flakes
      - mkdir -p ~/.config/nix
      - echo -e "
          experimental-features = nix-command flakes\n
          substituters = http://attic.app-attic.svc/main\n
          trusted-public-keys = main:1jU1/ydAUG+eKm24k9MMGP13Bv+MmgxPyf169DNHZRM=
        " > ~/.config/nix/nix.conf
      # make sure attic-client is cached or buildable locally, fetch from cache.nixos.org if not
      - nix-shell -p attic-client --run true || {
          mv ~/.config/nix/nix.conf{,.bk};
          nix-shell -p attic-client --run true;
          mv ~/.config/nix/nix.conf{.bk,};
        }
      # start continuously caching to attic
      - nix-shell -p attic-client --run "attic login az http://attic.app-attic.svc $ATTIC_TOKEN"
      - nix-shell -p attic-client --run "attic watch-store main -j 16" & sleep 5
      - sleep 5
      # download/build alejandra
      - nix-shell -p alejandra --run true || {
          mv ~/.config/nix/nix.conf{,.bk};
          nix-shell -p alejandra --run true;
          mv ~/.config/nix/nix.conf{.bk,};
        }
      # format
      - nix-shell -p alejandra --run "alejandra --check ."
      # cache entire store to attic, just in case - || because attic fails if *any* path is invalid
      - nix-shell -p attic-client --run "
          find /nix/store -mindepth 1 -maxdepth 1 ! -name .links | attic push main --stdin --no-closure -j 16
          || find /nix/store -mindepth 1 -maxdepth 1 ! -name .links | xargs -L 16 attic push main --no-closure"
    backend_options: *secctx-backend-options
