variables:
  # doesn't seem to be any way to define this via env var
  - &secctx-backend-options
    kubernetes:
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

when:
  - event: cron
    cron: daily # needs to be defined in woodpecker webUI, @daily
    branch: main
  - event: manual

clone:
  git:
    image: woodpeckerci/plugin-git:2.7.0
    settings:
      recursive: true
      submodule-update-remote: true
    backend_options: *secctx-backend-options

steps:
  - name: update flake.lock
    image: nixos/nix:2.32.0
    commands:
      - ./core/scripts/ci/flake-update
    backend_options: *secctx-backend-options
  - name: commit & push flake update
    image: appleboy/drone-git-push:1.1.1
    settings:
      remote:
        from_secret: REMOTE_URL # https://woodpecker-ci:<passwd>@git.azey.net/<repo>
      branch: main
      local_ref: main
      commit: true
      commit_message: "treewide: auto-update"
      author_name: "woodpecker-ci"
      author_email: "woodpecker-noreply@azey.net"
    backend_options: *secctx-backend-options
