variables:
  # doesn't seem to be any way to define this via env var
  - &secctx-backend-options
    kubernetes:
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

when:
  - event: push
    branch: main
  - event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
    backend_options: *secctx-backend-options

steps:
  - name: build & cache
    image: nixos/nix
    environment:
      ATTIC_TOKEN:
        from_secret: ATTIC_TOKEN
    commands:
      # manually enable attic cache
      - mkdir -p ~/.config/nix
      - echo -e "substituters = http://attic.app-attic.svc/main https://cache.nixos.org\ntrusted-public-keys = main:1jU1/ydAUG+eKm24k9MMGP13Bv+MmgxPyf169DNHZRM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" > ~/.config/nix/nix.conf
      # login & use attic
      - nix-shell -p attic-client --run "attic login az http://attic.app-attic.svc $ATTIC_TOKEN"
      - nix-shell -p attic-client --run "attic use main"
      # first attempt build without caching, if that fails use default substituters
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes --option substituters http://attic.app-attic.svc/main flake check --all-systems || nix --extra-experimental-features nix-command --extra-experimental-features flakes flake check --all-systems
      # cache everything to attic
      - nix-shell -p attic-client --run "find /nix/store -mindepth 1 -maxdepth 1 ! -name .links | attic push main --stdin --no-closure -j 16"
    backend_options: *secctx-backend-options
