variables:
  # doesn't seem to be any way to define this via env var
  - &secctx-backend-options
    kubernetes:
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

when:
  - event: push
    branch: main
  - event: manual

clone:
  git:
    image: woodpeckerci/plugin-git:2.7.0
    settings:
      recursive: true
    backend_options: *secctx-backend-options

steps:
  - name: format & cache
    image: nixos/nix:2.32.0
    environment:
      ATTIC_TOKEN:
        from_secret: ATTIC_TOKEN
    commands:
      - ./core/scripts/ci/check-format
    backend_options: *secctx-backend-options
